// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function GetTopProcesses() {
  return window['go']['main']['App']['GetTopProcesses']();
}

export function GetWeather() {
  return window['go']['main']['App']['GetWeather']();
}

export function MFAAddAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['MFAAddAccount'](arg1, arg2, arg3);
}

export function MFAClearPin() {
  return window['go']['main']['App']['MFAClearPin']();
}

export function MFAGetCodes() {
  return window['go']['main']['App']['MFAGetCodes']();
}

export function MFAGetStatus() {
  return window['go']['main']['App']['MFAGetStatus']();
}

export function MFAListAccounts() {
  return window['go']['main']['App']['MFAListAccounts']();
}

export function MFALock() {
  return window['go']['main']['App']['MFALock']();
}

export function MFARemoveAccount(arg1) {
  return window['go']['main']['App']['MFARemoveAccount'](arg1);
}

export function MFASetPin(arg1) {
  return window['go']['main']['App']['MFASetPin'](arg1);
}

export function MFAUnlock(arg1) {
  return window['go']['main']['App']['MFAUnlock'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Views() {
  return window['go']['main']['App']['Views']();
}
