// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {github} from '../models';
import {main} from '../models';
import {sysstats} from '../models';
import {teams} from '../models';
import {weather} from '../models';
import {config} from '../models';

export function GetGitHubPRs():Promise<github.Result>;

export function GetGitHubReviews():Promise<github.Result>;

export function GetGitHubWorkflows():Promise<github.WorkflowResult>;

export function GetSettings():Promise<main.Settings>;

export function GetSystemStats():Promise<sysstats.Stats>;

export function GetTeamsUnread():Promise<teams.Result>;

export function GetTopProcesses():Promise<Array<sysstats.Process>>;

export function GetWeather():Promise<weather.Data>;

export function MFAAddAccount(arg1:string,arg2:string,arg3:string):Promise<config.TotpAccount>;

export function MFAClearPin():Promise<void>;

export function MFAGetCodes():Promise<main.MFACodes>;

export function MFAGetStatus():Promise<main.MFAStatus>;

export function MFAListAccounts():Promise<Array<config.TotpAccount>>;

export function MFALock():Promise<void>;

export function MFARemoveAccount(arg1:string):Promise<void>;

export function MFASetPin(arg1:string):Promise<void>;

export function MFAUnlock(arg1:string):Promise<boolean>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function TeamsConfigured():Promise<boolean>;

export function TeamsLoggedIn():Promise<boolean>;

export function TeamsLogin():Promise<void>;

export function Views():Promise<Array<string>>;
